services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5038:8080"                # Swagger: http://localhost:5038/swagger
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - DISABLE_HTTPS_REDIRECT=true   # garante HTTP puro no container
      # Se precisar forçar um caminho absoluto por ENV:
      # - ConnectionStrings__DefaultConnection=Data Source=/app/lixoZero.db
    volumes:
      - ./lixoZero.db:/app/lixoZero.db:rw
    networks:
      - lixo_net
    restart: unless-stopped

networks:
  lixo_net:
