// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace LixoZero.Specs.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "api")]
    [Xunit.TraitAttribute("Category", "cadastro")]
    [Xunit.TraitAttribute("Category", "status")]
    [Xunit.TraitAttribute("Category", "contrato")]
    public partial class CadastroDeDescarteFeature : object, Xunit.IClassFixture<CadastroDeDescarteFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "api",
                "cadastro",
                "status",
                "contrato"};
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "01_cadastro_descarte.feature"
#line hidden
        
        public CadastroDeDescarteFeature(CadastroDeDescarteFeature.FixtureData fixtureData, LixoZero_Specs_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt"), "Features", "Cadastro de Descarte", null, ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 5
  #line hidden
#line 6
testRunner.Given("que a base URL da API é \"http://localhost:5038\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cadastrar descarte válido retorna 201 e corpo no contrato")]
        [Xunit.TraitAttribute("FeatureTitle", "Cadastro de Descarte")]
        [Xunit.TraitAttribute("Description", "Cadastrar descarte válido retorna 201 e corpo no contrato")]
        public void CadastrarDescarteValidoRetorna201ECorpoNoContrato()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cadastrar descarte válido retorna 201 e corpo no contrato", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 8
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
  this.FeatureBackground();
#line hidden
#line 9
    testRunner.When("eu fizer POST para \"/api/Descartes\" com o corpo JSON:", "{ \"bairro\":\"Centro\", \"tipo\":0, \"quantidadeKg\":0.25, \"dataHora\":\"2025-10-10T22:09:" +
                        "47.709Z\" }", ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 13
    testRunner.Then("o status da resposta deve ser 201", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 14
    testRunner.And("o corpo JSON deve obedecer ao schema \"Schemas/descarte.schema.json\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 15
    testRunner.And("o campo \"bairro\" deve ser \"Centro\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 16
    testRunner.And("o campo \"tipo\" deve ser 0", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 17
    testRunner.And("o campo \"quantidadeKg\" deve ser 0.25", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cadastrar descarte inválido (quantidade <= 0) retorna 400")]
        [Xunit.TraitAttribute("FeatureTitle", "Cadastro de Descarte")]
        [Xunit.TraitAttribute("Description", "Cadastrar descarte inválido (quantidade <= 0) retorna 400")]
        public void CadastrarDescarteInvalidoQuantidade0Retorna400()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cadastrar descarte inválido (quantidade <= 0) retorna 400", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 19
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
  this.FeatureBackground();
#line hidden
#line 20
    testRunner.When("eu fizer POST para \"/api/Descartes\" com o corpo JSON:", "{ \"bairro\":\"Centro\", \"tipo\":0, \"quantidadeKg\":0, \"dataHora\":\"2025-10-10T22:09:47." +
                        "709Z\" }", ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 24
    testRunner.Then("o status da resposta deve ser 400", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                CadastroDeDescarteFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                CadastroDeDescarteFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
