name: CI/CD - LixoZero

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restaurar dependências
        run: |
          dotnet restore LixoZero.csproj
          dotnet restore LixoZero.Tests.csproj


      - name: Compilar o projeto (Release)
        run: dotnet build LixoZero.sln --configuration Release --no-restore

      - name: Executar testes
        run: dotnet test LixoZero.Tests.csproj --no-build --verbosity normal
      - name: Publicar aplicação
        run: dotnet publish LixoZero.csproj -c Release -o ./out

      - name: Upload da build (artefato)
        uses: actions/upload-artifact@v4
        with:
          name: LixoZero-Build
          path: ./out
